import shutil
import os

class OracleInjector:
    """
    Takes the oracle generated by the LLM and
    inserts it into a copy of the test file.
    """

    def inject(self, original_test_path, generated_oracle, output_path):
        # Make a copy of the original — never change the original file
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        shutil.copy(original_test_path, output_path)

        # Read the copy
        with open(output_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Clean up the LLM response
        oracle = self._clean_oracle(generated_oracle)

        # Replace the placeholder with the real oracle
        if "// [ORACLE REMOVED]" in content:
            content = content.replace("// [ORACLE REMOVED]", oracle)
        else:
            print(f"  WARNING: Could not find placeholder in {output_path}")

        # Save the modified file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        return output_path

    def _clean_oracle(self, raw_response):
        """Remove markdown formatting the LLM sometimes adds"""
        lines = raw_response.strip().split("\n")
        clean = [
            line for line in lines
            if not line.strip().startswith("```")
        ]
        return "\n        ".join(clean)